= About

Sample application to test certain features of the Java Enterprise Edition platform: JAX-RS, CDI, managed JPA contexts.

== Requirements

* Oracle JDK 1.8
* Oracle 11g Express Edition (11.2.0.2.0)
* WebLogic 12c (12.2.1.3.0)

== Notes

* Install the Oracle 11g XE database.
Use Docker if possible it's much easier that way on Ubuntu, etc.
* Create a new schema (user) for the application called `bank`.
This creates a new user called `bank` but it won't have privilege to connect to the database.
Execute `GRANT ALL PRIVILEGES TO bank;` with `SYS` or `SYSTEM` to grant privileges to the user.
* Install WebLogic using the steps described in its `README.txt` file.
Follow the wizard, use defaults.
Alternatively use Docker.
* Create a data source in WebLogic.
* It's JNDI name *must be different* then its symbolic name.
E.g. https://stackoverflow.com/a/39876437/433835[if its symbolic name is `bank` then use something like `jdbc/bankDS`].
* The database name to connect to is XE (the SID), the user to conntect with is `bank`, everything should be left at
its default setting.
* Make sure to deploy to the target server otherwise applications won't be able to access it.
* The link:build.gradle[Gradle build script] only contains the `javaee-api` dependency on purpose, the scope is
`compileOnly` because we don't want to include the JARs in the WAR built by Gradle—it's provided by WebLogic.
* In order to dependency injection to work link:src/main/webapp/WEB-INF/beans.xml[beans.xml] must be included in the WAR.
* link:META-INF/persistence.xml[persistence.xml] refers to `jdbc/bankDS` and defines scripts to be run when the application
is deployed.
* *Very important* that the scripts (`{drop,create,load}.sql`) *_must_* contain statements in a single line and
*_cannot_* contain a trailing semi-colon.
This is a short-coming of EclipseLink (see https://github.com/payara/Payara/issues/874[here] and https://stackoverflow.com/q/21729097/433835[here]).
* In order for objects to be serialized to JSON properly they must be annotated with `@XmlElementRoot`.
See link:src/main/java/com/codecool/bank/dto/BankcardDto.java[`BankcardDto`].
Other aspects of the JSON serialization can be controlled with other JAXB annotations like `@XmlElement`, etc.
* Methods making DML calls must be executing in a transaction.
Methods like this must be marked with `@Transactional`, otherwise the database won't reflect changes and no errors will be raised.
* To run the integration tests the application must be already deployed to WebLogic under the `bank` symbolic name.
* For quick redeployment use https://docs.oracle.com/middleware/12213/cross/wlsttasks.htm[WLST].
Find the `setWlstEnv.{sh,cmd}` script in your installation and run it in the terminal.
It'll modify the `CLASSPATH` environment variable and append WebLogic's WSLT JAR's path to it.
Then run `java weblogic.WSLT` and it'll drop you into the WSLT prompt.
Run `connect` then `redeploy('bank', appPath='path/to/the/WAR')`.
Subsequent redeploys can be simply `redeploy('bank')`.
